### PR TITLE
Reduce code duplication in Wasm runner

### PR DESCRIPTION
**Pull request by danleh**
We previously had this in the WebKit repo at https://github.com/WebKit/WebKit/pull/34572, but let's keep all the work here in this separate repo. I hope it's fine to go without a radare/WebKit issue, which would streamline working in here a bit.

### CODE REVIEW

**Review by kmiller68 — APPROVED** [review]
LGTM

**Comment by danleh** [comment]
Awesome, merge? ("I have no power here" :-) )

**Comment by kmiller68** [comment]
> I hope it's fine to go without a radar/WebKit issue, which would streamline working in here a bit.

Yeah, I think we should run it like the Speedometer repo. If needed we can template in the future.

**Comment by danleh** [comment]
Sure, I didn't participate in Speedometer, so let me know what the process is (or let's discuss in a bit).

**Pull request merged**
